
SUBDIR_1 = CircuitRouter-Service
SUBDIR_2 = CircuitRouter-SeqSolver

all:
	$(MAKE) -C $(SUBDIR_1)
	$(MAKE) -C $(SUBDIR_2)

clean:
	$(MAKE) clean -C $(SUBDIR_1)
	$(MAKE) clean -C $(SUBDIR_2)
